# Generated by Django 5.2.6 on 2025-09-11 20:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=64)),
                ('original_name', models.TextField()),
                ('storage_path', models.TextField(unique=True)),
                ('mime_type', models.TextField(blank=True, null=True)),
                ('size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('checksum_sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('adapter_hint', models.CharField(choices=[('csv', 'Csv'), ('ofx', 'Ofx'), ('qif', 'Qif'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('source_hint', models.CharField(choices=[('otp', 'Otp'), ('revolut', 'Revolut'), ('ibkr', 'Ibkr'), ('other', 'Other')], default='other', max_length=16)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('queued', 'Queued'), ('processing', 'Processing'), ('parsed', 'Parsed'), ('failed', 'Failed')], default='uploaded', max_length=16)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
